apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-service
spec:
  replicas: 11
  selector:
    matchLabels:
      app: python-service
  template:
    metadata:
      labels:
        app: python-service
    spec:
      containers:
        - name: python
          image: kimlong92018892/python-service
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  type: NodePort
  selector:
    app: python-service
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500